package com.everrefine.elms.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.media.Content;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.ObjectSchema;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;
import org.springdoc.core.customizers.OpenApiCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpStatus;

/** Swagger/OpenAPI設定。 */
@Configuration
public class SwaggerConfig {

  /**
   * OpenAPI定義を生成する。
   *
   * @return OpenAPI定義
   */
  @Bean
  public OpenAPI openAPI() {
    return new OpenAPI()
        .info(
            new Info()
                .title("e-learning-management-system API")
                .description("e-learning-management-system API")
                .version("1.0.0"))
        .addSecurityItem(new SecurityRequirement().addList("bearerAuth"))
        .components(
            new Components()
                .addSchemas(
                    "ErrorResponse",
                    new ObjectSchema()
                        .description("エラーレスポンス")
                        .addProperty(
                            "code",
                            new StringSchema().description("エラーコード").example("RESOURCE_NOT_FOUND"))
                        .addProperty(
                            "message",
                            new StringSchema().description("エラーメッセージ").example("リソースが見つかりません")))
                .addSecuritySchemes(
                    "bearerAuth",
                    new SecurityScheme()
                        .type(SecurityScheme.Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")));
  }

  /**
   * springdocが {@code @RestControllerAdvice} から全エンドポイントへ自動付与するレスポンスを取り除くカスタマイザーを生成する。
   *
   * <p>springdocは例外ハンドラの定義を全エンドポイントに一律で追加するため、実際にはその status を返さない エンドポイントにも 400 / 404 / 500
   * が現れてしまう。自動付与されたものはHTTPの標準理由句が説明文になるので、それを目印に取り除き、コントローラーで宣言した {@code @ApiResponse} だけを残す。
   *
   * <p>自動付与時の説明文は、springdocの {@code GenericResponseService#setDescription} が Springの {@code
   * HttpStatus#getReasonPhrase()} をそのまま設定したもの。そのため判定用の文字列は列挙せず、 {@code HttpStatus}
   * の全定義から導出する。こうすることで例外ハンドラが増えてもこのクラスの修正が不要になり、 Springのバージョンアップによる理由句の変更にも追従できる。
   *
   * <p>コントローラー側の {@code @ApiResponse} は説明文を日本語で書くため、この英語の理由句と衝突することはない。
   *
   * @return OpenAPIカスタマイザー
   */
  @Bean
  @Order(1)
  public OpenApiCustomizer declaredResponsesOnlyCustomizer() {
    Set<String> autoGeneratedDescriptions =
        Arrays.stream(HttpStatus.values())
            .map(HttpStatus::getReasonPhrase)
            .collect(Collectors.toUnmodifiableSet());
    return openApi ->
        openApi
            .getPaths()
            .values()
            .forEach(
                pathItem ->
                    pathItem
                        .readOperations()
                        .forEach(
                            operation ->
                                operation
                                    .getResponses()
                                    .entrySet()
                                    .removeIf(
                                        entry ->
                                            autoGeneratedDescriptions.contains(
                                                entry.getValue().getDescription()))));
  }

  /**
   * 全エンドポイントに共通で発生しうるレスポンスを付与するカスタマイザーを生成する。
   *
   * <p>405 / 415 / 500 はフレームワーク由来で、どのエンドポイントでも発生しうる。コントローラーの {@code @ApiResponse}
   * には業務上意味のあるコードだけを書き、共通のものはここで一括付与することで、 39エンドポイントすべてに同じ宣言が並ぶのを避けている。
   *
   * <p>415はリクエストボディを受け取るエンドポイントにのみ付与する。
   *
   * @return OpenAPIカスタマイザー
   */
  @Bean
  @Order(2)
  public OpenApiCustomizer commonResponsesCustomizer() {
    return openApi ->
        openApi
            .getPaths()
            .values()
            .forEach(
                pathItem ->
                    pathItem
                        .readOperations()
                        .forEach(
                            operation -> {
                              ApiResponses responses = operation.getResponses();
                              responses.addApiResponse("405", describe("このHTTPメソッドはサポートされていません"));
                              responses.addApiResponse("500", describe("サーバーエラーが発生しました"));
                              if (operation.getRequestBody() != null) {
                                responses.addApiResponse(
                                    "415", describe("サポートされていないContent-Typeです"));
                              }
                            }));
  }

  /**
   * 説明文だけを持つレスポンス定義を生成する。スキーマは {@link #errorResponseCustomizer()} が適用する。
   *
   * @param description 説明文
   * @return レスポンス定義
   */
  private ApiResponse describe(String description) {
    return new ApiResponse().description(description);
  }

  /**
   * 全エンドポイントの4xx/5xxレスポンスにErrorResponseスキーマを自動適用するカスタマイザーを生成する。
   *
   * @return OpenAPIカスタマイザー
   */
  @Bean
  @Order(3)
  public OpenApiCustomizer errorResponseCustomizer() {
    var errorContent =
        new Content()
            .addMediaType(
                "application/json",
                new MediaType().schema(new Schema<>().$ref("#/components/schemas/ErrorResponse")));
    return openApi ->
        openApi
            .getPaths()
            .values()
            .forEach(
                pathItem ->
                    pathItem
                        .readOperations()
                        .forEach(
                            operation ->
                                operation
                                    .getResponses()
                                    .forEach(
                                        (code, response) -> {
                                          try {
                                            if (Integer.parseInt(code) >= 400) {
                                              response.setContent(errorContent);
                                            }
                                          } catch (NumberFormatException ignored) {
                                          }
                                        })));
  }
}
