version: '3.8'

services:
  elms-mailpit:
    image: axllent/mailpit
    container_name: elms-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  elms-db:
    image: postgres:17
    container_name: elms-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: elms_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      TZ: Asia/Tokyo
    volumes:
      - elms-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  elms-db-data:
